### ISSUE TITLE
No package.json file

### ISSUE THREAD

**Issue by rcarcasses** [mudasobwa/eblox#1]
So is impossible to do npm install, any help?

Best,
Robert

**Comment by am-kantox** [comment]
As it is Phoenix 1.3, you need to `cd assets && npm install`. It’s the default in Phoenix since 1.3.

Please note that this project is in very early stage, and I would say it’s not yet reached the MVP. I hopefully will make it robust in a matter of days (since I need it myself) and I will write the how-to.

I would hint you to wait to try it until 1.0 version :) Though the idea itself is very promising.

**Comment by rcarcasses** [comment]
Okay thank you and keep the good job!
